version: '3.8'

services:
  debian12:
    image: debian:12
    container_name: debian12_container
    privileged: true
    ports:
      - "22:22"
      - "8006:8006"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /proc:/proc
      - /dev:/dev
      - /run/systemd:/run/systemd
    environment:
      - container=docker
    command: >
      bash -c "
      apt update && apt install -y sudo systemd systemd-sysv openssh-server &&
      useradd -m -s /bin/bash user &&
      echo 'user ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      mkdir -p /var/run/sshd &&
      /sbin/init"
    restart: unless-stopped
