name: Dockermox 

on: 
  workflow_dispatch:
 
jobs:
  dockermox:
    runs-on: ubuntu-22.04
    steps:

      - name: Getting Updates and Installing Tailscale.
        run: |
          sudo apt update -y
          sudo apt install docker.io -y
          sudo curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --ssh
      - name: Provisioning and running Docker.
        run: |
          sudo wget -qO docker-compose.yml https://raw.githubusercontent.com/398103481wdawd/idk/refs/heads/main/compose.yaml
          docker-compose up --build    
