name: Dockermox 

on: 
  workflow_dispatch:
 
jobs:
  dockermox:
    runs-on: ubuntu-24.04
    steps:

      - name: Getting Updates and Installing Tailscale.
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-compose
          curl -fsSL https://tailscale.com/install.sh | sh 
          sudo tailscale up
          sudo apt remove --purge openssh* -y
      - name: Provisioning and running Docker.
        run: |
          sudo docker pull debian:12
          echo "version: '3.8'
                services:
                  debian12:
                    image: debian:12
                    container_name: debian12_container
                    privileged: true
                    ports:
                      - \"22:22\"
                      - \"8006:8006\"
                    volumes:
                      - /sys/fs/cgroup:/sys/fs/cgroup:ro
                      - /proc:/proc
                      - /dev:/dev
                      - /run/systemd:/run/systemd
                    environment:
                      - container=docker
                    command: >
                      bash -c \"
                        apt update &&
                        apt install systemd systemd-sysv -y &&
                        echo \"root:root\" | chpasswd &&
                        /sbin/init\"
                   restart: unless-stopped" > docker-compose.yml
          docker-compose up --build    
